export const AUTH_OAUTH_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_OAUTH_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_OAUTH_MODULE_SETTINGS_TOKEN =
  'AUTH_OAUTH_MODULE_SETTINGS_TOKEN';

export const AUTH_OAUTH_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_OAUTH_MODULE_DEFAULT_SETTINGS_TOKEN';

export const OAUTH_CONFIG_TOKEN = 'OAUTH_CONFIG_TOKEN';

export const OAUTH_MODULE_GUARDS_TOKEN = 'OAUTH_MODULE_GUARDS_TOKEN';

export const AUTH_OAUTH_STRATEGY_NAME = 'oauth';
