export const AUTHENTICATION_MODULE_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_SETTINGS_TOKEN';

export const ROCKETS_SERVER_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN = 'ROCKETS_SERVER_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN';

export const AUTHENTICATION_MODULE_VALIDATE_TOKEN_SERVICE_TOKEN =
  'AUTHENTICATION_MODULE_VALIDATE_TOKEN_SERVICE_TOKEN';

export const AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN =
  'AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN';

