export const AUTH_ROUTER_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_ROUTER_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_ROUTER_MODULE_SETTINGS_TOKEN =
  'AUTH_ROUTER_MODULE_SETTINGS_TOKEN';

export const AUTH_ROUTER_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_ROUTER_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_ROUTER_CONFIG_TOKEN = 'AUTH_ROUTER_CONFIG_TOKEN';

export const AuthRouterModuleGuards = Symbol('AUTH_ROUTER_MODULE_GUARDS_TOKEN');

export const AUTH_ROUTER_STRATEGY_NAME = 'auth-router';
