import { ComparisonOperator } from './types/crud-request-query.types';

export const COMPARISON_OPERATORS: ReadonlyArray<ComparisonOperator> = [
  '$eq',
  '$ne',
  '$gt',
  '$lt',
  '$gte',
  '$lte',
  '$starts',
  '$ends',
  '$cont',
  '$excl',
  '$in',
  '$notin',
  '$between',
  '$isnull',
  '$notnull',
  '$eqL',
  '$neL',
  '$startsL',
  '$endsL',
  '$contL',
  '$exclL',
  '$inL',
  '$notinL',
  '$or',
  '$and',
] as const;
