export const AUTH_GUARD_ROUTER_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_GUARD_ROUTER_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_GUARD_ROUTER_MODULE_SETTINGS_TOKEN =
  'AUTH_GUARD_ROUTER_MODULE_SETTINGS_TOKEN';

export const AUTH_GUARD_ROUTER_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_GUARD_ROUTER_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_GUARD_ROUTER_CONFIG_TOKEN = 'AUTH_GUARD_ROUTER_CONFIG_TOKEN';

export const AuthGuardRouterModuleGuards = Symbol(
  'AUTH_GUARD_ROUTER_MODULE_GUARDS_TOKEN',
);

export const AUTH_GUARD_ROUTER_STRATEGY_NAME = 'auth-guard-router';
